services:
  db:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bookshop
      - POSTGRES_USER=testu
      - POSTGRES_PASSWORD=testp
    volumes:
      - ./db-data:/var/lib/postgresql/data
